#############################################################################
# Makefile for building: barcodeGui
# Generated by qmake (2.01a) (Qt 4.7.4) on: Mon Jun 4 14:41:50 2012
# Project:  barcodeGui.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile barcodeGui.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/local/include/ImageMagick -I/usr/local/include -I/usr/local/include -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/home/sagaian/Desktop/cs194/barcodeDecoder2/../../../../../usr/local/lib/ -lMagick++ -lMagickCore -lMagickWand -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		multiBase.cpp \
		numberSystem.cpp \
		novelBarcodeDecorder.cpp \
		fibonacciSystem.cpp \
		decoder.cpp \
		numbersystemwidget.cpp \
		enhancer.cpp \
		goldenRatioSystem.cpp \
		chunker.cpp \
		encoder.cpp \
		securer.cpp \
		compressor.cpp \
		alphaConverter.cpp \
		analyzer.cpp \
		code39_Encoder.cpp moc_mainwindow.cpp \
		moc_numbersystemwidget.cpp
OBJECTS       = main.o \
		mainwindow.o \
		multiBase.o \
		numberSystem.o \
		novelBarcodeDecorder.o \
		fibonacciSystem.o \
		decoder.o \
		numbersystemwidget.o \
		enhancer.o \
		goldenRatioSystem.o \
		chunker.o \
		encoder.o \
		securer.o \
		compressor.o \
		alphaConverter.o \
		analyzer.o \
		code39_Encoder.o \
		moc_mainwindow.o \
		moc_numbersystemwidget.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		barcodeGui.pro
QMAKE_TARGET  = barcodeGui
DESTDIR       = 
TARGET        = barcodeGui

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_numbersystemwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: barcodeGui.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile barcodeGui.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile barcodeGui.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/barcodeGui1.0.0 || $(MKDIR) .tmp/barcodeGui1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/barcodeGui1.0.0/ && $(COPY_FILE) --parents mainwindow.h fibonacciSystem.h numberSystem.h multiBase.h goldenRatioSystem.h histogramResult.h decoder.h numbersystemwidget.h enhancer.h chunker.h encoder.h securer.h compressor.h alphaConverter.h analyzer.h code39_Encoder.h .tmp/barcodeGui1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp multiBase.cpp numberSystem.cpp novelBarcodeDecorder.cpp fibonacciSystem.cpp decoder.cpp numbersystemwidget.cpp enhancer.cpp goldenRatioSystem.cpp chunker.cpp encoder.cpp securer.cpp compressor.cpp alphaConverter.cpp analyzer.cpp code39_Encoder.cpp .tmp/barcodeGui1.0.0/ && $(COPY_FILE) --parents mainwindow.ui numbersystemwidget.ui .tmp/barcodeGui1.0.0/ && (cd `dirname .tmp/barcodeGui1.0.0` && $(TAR) barcodeGui1.0.0.tar barcodeGui1.0.0 && $(COMPRESS) barcodeGui1.0.0.tar) && $(MOVE) `dirname .tmp/barcodeGui1.0.0`/barcodeGui1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/barcodeGui1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_numbersystemwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_numbersystemwidget.cpp
moc_mainwindow.cpp: numberSystem.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_numbersystemwidget.cpp: numberSystem.h \
		numbersystemwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) numbersystemwidget.h -o moc_numbersystemwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_numbersystemwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_numbersystemwidget.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_numbersystemwidget.h: numbersystemwidget.ui
	/usr/bin/uic-qt4 numbersystemwidget.ui -o ui_numbersystemwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		numberSystem.h \
		fibonacciSystem.h \
		alphaConverter.h \
		multiBase.h \
		securer.h \
		/usr/local/include/ImageMagick/Magick++.h \
		/usr/local/include/ImageMagick/Magick++/Include.h \
		/usr/local/include/ImageMagick/magick/magick-config.h \
		/usr/local/include/ImageMagick/magick/MagickCore.h \
		/usr/local/include/ImageMagick/magick/method-attribute.h \
		/usr/local/include/ImageMagick/magick/methods.h \
		/usr/local/include/ImageMagick/magick/magick-type.h \
		/usr/local/include/ImageMagick/magick/accelerate.h \
		/usr/local/include/ImageMagick/magick/morphology.h \
		/usr/local/include/ImageMagick/magick/geometry.h \
		/usr/local/include/ImageMagick/magick/animate.h \
		/usr/local/include/ImageMagick/magick/annotate.h \
		/usr/local/include/ImageMagick/magick/draw.h \
		/usr/local/include/ImageMagick/magick/image.h \
		/usr/local/include/ImageMagick/magick/color.h \
		/usr/local/include/ImageMagick/magick/pixel.h \
		/usr/local/include/ImageMagick/magick/colorspace.h \
		/usr/local/include/ImageMagick/magick/constitute.h \
		/usr/local/include/ImageMagick/magick/exception.h \
		/usr/local/include/ImageMagick/magick/semaphore.h \
		/usr/local/include/ImageMagick/magick/blob.h \
		/usr/local/include/ImageMagick/magick/stream.h \
		/usr/local/include/ImageMagick/magick/cache-view.h \
		/usr/local/include/ImageMagick/magick/composite.h \
		/usr/local/include/ImageMagick/magick/compress.h \
		/usr/local/include/ImageMagick/magick/effect.h \
		/usr/local/include/ImageMagick/magick/layer.h \
		/usr/local/include/ImageMagick/magick/locale_.h \
		/usr/local/include/ImageMagick/magick/hashmap.h \
		/usr/local/include/ImageMagick/magick/monitor.h \
		/usr/local/include/ImageMagick/magick/profile.h \
		/usr/local/include/ImageMagick/magick/string_.h \
		/usr/local/include/ImageMagick/magick/quantum.h \
		/usr/local/include/ImageMagick/magick/resample.h \
		/usr/local/include/ImageMagick/magick/resize.h \
		/usr/local/include/ImageMagick/magick/timer.h \
		/usr/local/include/ImageMagick/magick/type.h \
		/usr/local/include/ImageMagick/magick/artifact.h \
		/usr/local/include/ImageMagick/magick/attribute.h \
		/usr/local/include/ImageMagick/magick/cache.h \
		/usr/local/include/ImageMagick/magick/cipher.h \
		/usr/local/include/ImageMagick/magick/client.h \
		/usr/local/include/ImageMagick/magick/coder.h \
		/usr/local/include/ImageMagick/magick/colormap.h \
		/usr/local/include/ImageMagick/magick/compare.h \
		/usr/local/include/ImageMagick/magick/configure.h \
		/usr/local/include/ImageMagick/magick/decorate.h \
		/usr/local/include/ImageMagick/magick/delegate.h \
		/usr/local/include/ImageMagick/magick/deprecate.h \
		/usr/local/include/ImageMagick/magick/quantize.h \
		/usr/local/include/ImageMagick/magick/registry.h \
		/usr/local/include/ImageMagick/magick/display.h \
		/usr/local/include/ImageMagick/magick/distort.h \
		/usr/local/include/ImageMagick/magick/enhance.h \
		/usr/local/include/ImageMagick/magick/feature.h \
		/usr/local/include/ImageMagick/magick/fourier.h \
		/usr/local/include/ImageMagick/magick/fx.h \
		/usr/local/include/ImageMagick/magick/gem.h \
		/usr/local/include/ImageMagick/magick/random_.h \
		/usr/local/include/ImageMagick/magick/histogram.h \
		/usr/local/include/ImageMagick/magick/identify.h \
		/usr/local/include/ImageMagick/magick/image-view.h \
		/usr/local/include/ImageMagick/magick/list.h \
		/usr/local/include/ImageMagick/magick/log.h \
		/usr/local/include/ImageMagick/magick/magic.h \
		/usr/local/include/ImageMagick/magick/magick.h \
		/usr/local/include/ImageMagick/magick/matrix.h \
		/usr/local/include/ImageMagick/magick/memory_.h \
		/usr/local/include/ImageMagick/magick/module.h \
		/usr/local/include/ImageMagick/magick/version.h \
		/usr/local/include/ImageMagick/magick/mime.h \
		/usr/local/include/ImageMagick/magick/montage.h \
		/usr/local/include/ImageMagick/magick/option.h \
		/usr/local/include/ImageMagick/magick/paint.h \
		/usr/local/include/ImageMagick/magick/policy.h \
		/usr/local/include/ImageMagick/magick/prepress.h \
		/usr/local/include/ImageMagick/magick/property.h \
		/usr/local/include/ImageMagick/magick/resource_.h \
		/usr/local/include/ImageMagick/magick/segment.h \
		/usr/local/include/ImageMagick/magick/shear.h \
		/usr/local/include/ImageMagick/magick/signature.h \
		/usr/local/include/ImageMagick/magick/splay-tree.h \
		/usr/local/include/ImageMagick/magick/statistic.h \
		/usr/local/include/ImageMagick/magick/token.h \
		/usr/local/include/ImageMagick/magick/transform.h \
		/usr/local/include/ImageMagick/magick/threshold.h \
		/usr/local/include/ImageMagick/magick/utility.h \
		/usr/local/include/ImageMagick/magick/xml-tree.h \
		/usr/local/include/ImageMagick/magick/xwindow.h \
		/usr/local/include/ImageMagick/wand/MagickWand.h \
		/usr/local/include/ImageMagick/wand/method-attribute.h \
		/usr/local/include/ImageMagick/wand/animate.h \
		/usr/local/include/ImageMagick/wand/compare.h \
		/usr/local/include/ImageMagick/wand/composite.h \
		/usr/local/include/ImageMagick/wand/conjure.h \
		/usr/local/include/ImageMagick/wand/convert.h \
		/usr/local/include/ImageMagick/wand/deprecate.h \
		/usr/local/include/ImageMagick/wand/drawing-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-wand.h \
		/usr/local/include/ImageMagick/wand/magick-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-iterator.h \
		/usr/local/include/ImageMagick/wand/display.h \
		/usr/local/include/ImageMagick/wand/identify.h \
		/usr/local/include/ImageMagick/wand/import.h \
		/usr/local/include/ImageMagick/wand/magick-property.h \
		/usr/local/include/ImageMagick/wand/magick-image.h \
		/usr/local/include/ImageMagick/wand/mogrify.h \
		/usr/local/include/ImageMagick/wand/montage.h \
		/usr/local/include/ImageMagick/wand/stream.h \
		/usr/local/include/ImageMagick/wand/wand-view.h \
		/usr/local/include/ImageMagick/Magick++/Image.h \
		/usr/local/include/ImageMagick/Magick++/Blob.h \
		/usr/local/include/ImageMagick/Magick++/Color.h \
		/usr/local/include/ImageMagick/Magick++/Drawable.h \
		/usr/local/include/ImageMagick/Magick++/Geometry.h \
		/usr/local/include/ImageMagick/Magick++/Exception.h \
		/usr/local/include/ImageMagick/Magick++/TypeMetric.h \
		/usr/local/include/ImageMagick/Magick++/Pixels.h \
		/usr/local/include/ImageMagick/Magick++/STL.h \
		/usr/local/include/ImageMagick/Magick++/CoderInfo.h \
		/usr/local/include/ImageMagick/Magick++/Montage.h \
		compressor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		numberSystem.h \
		ui_mainwindow.h \
		/usr/local/include/ImageMagick/Magick++.h \
		/usr/local/include/ImageMagick/Magick++/Include.h \
		/usr/local/include/ImageMagick/magick/magick-config.h \
		/usr/local/include/ImageMagick/magick/MagickCore.h \
		/usr/local/include/ImageMagick/magick/method-attribute.h \
		/usr/local/include/ImageMagick/magick/methods.h \
		/usr/local/include/ImageMagick/magick/magick-type.h \
		/usr/local/include/ImageMagick/magick/accelerate.h \
		/usr/local/include/ImageMagick/magick/morphology.h \
		/usr/local/include/ImageMagick/magick/geometry.h \
		/usr/local/include/ImageMagick/magick/animate.h \
		/usr/local/include/ImageMagick/magick/annotate.h \
		/usr/local/include/ImageMagick/magick/draw.h \
		/usr/local/include/ImageMagick/magick/image.h \
		/usr/local/include/ImageMagick/magick/color.h \
		/usr/local/include/ImageMagick/magick/pixel.h \
		/usr/local/include/ImageMagick/magick/colorspace.h \
		/usr/local/include/ImageMagick/magick/constitute.h \
		/usr/local/include/ImageMagick/magick/exception.h \
		/usr/local/include/ImageMagick/magick/semaphore.h \
		/usr/local/include/ImageMagick/magick/blob.h \
		/usr/local/include/ImageMagick/magick/stream.h \
		/usr/local/include/ImageMagick/magick/cache-view.h \
		/usr/local/include/ImageMagick/magick/composite.h \
		/usr/local/include/ImageMagick/magick/compress.h \
		/usr/local/include/ImageMagick/magick/effect.h \
		/usr/local/include/ImageMagick/magick/layer.h \
		/usr/local/include/ImageMagick/magick/locale_.h \
		/usr/local/include/ImageMagick/magick/hashmap.h \
		/usr/local/include/ImageMagick/magick/monitor.h \
		/usr/local/include/ImageMagick/magick/profile.h \
		/usr/local/include/ImageMagick/magick/string_.h \
		/usr/local/include/ImageMagick/magick/quantum.h \
		/usr/local/include/ImageMagick/magick/resample.h \
		/usr/local/include/ImageMagick/magick/resize.h \
		/usr/local/include/ImageMagick/magick/timer.h \
		/usr/local/include/ImageMagick/magick/type.h \
		/usr/local/include/ImageMagick/magick/artifact.h \
		/usr/local/include/ImageMagick/magick/attribute.h \
		/usr/local/include/ImageMagick/magick/cache.h \
		/usr/local/include/ImageMagick/magick/cipher.h \
		/usr/local/include/ImageMagick/magick/client.h \
		/usr/local/include/ImageMagick/magick/coder.h \
		/usr/local/include/ImageMagick/magick/colormap.h \
		/usr/local/include/ImageMagick/magick/compare.h \
		/usr/local/include/ImageMagick/magick/configure.h \
		/usr/local/include/ImageMagick/magick/decorate.h \
		/usr/local/include/ImageMagick/magick/delegate.h \
		/usr/local/include/ImageMagick/magick/deprecate.h \
		/usr/local/include/ImageMagick/magick/quantize.h \
		/usr/local/include/ImageMagick/magick/registry.h \
		/usr/local/include/ImageMagick/magick/display.h \
		/usr/local/include/ImageMagick/magick/distort.h \
		/usr/local/include/ImageMagick/magick/enhance.h \
		/usr/local/include/ImageMagick/magick/feature.h \
		/usr/local/include/ImageMagick/magick/fourier.h \
		/usr/local/include/ImageMagick/magick/fx.h \
		/usr/local/include/ImageMagick/magick/gem.h \
		/usr/local/include/ImageMagick/magick/random_.h \
		/usr/local/include/ImageMagick/magick/histogram.h \
		/usr/local/include/ImageMagick/magick/identify.h \
		/usr/local/include/ImageMagick/magick/image-view.h \
		/usr/local/include/ImageMagick/magick/list.h \
		/usr/local/include/ImageMagick/magick/log.h \
		/usr/local/include/ImageMagick/magick/magic.h \
		/usr/local/include/ImageMagick/magick/magick.h \
		/usr/local/include/ImageMagick/magick/matrix.h \
		/usr/local/include/ImageMagick/magick/memory_.h \
		/usr/local/include/ImageMagick/magick/module.h \
		/usr/local/include/ImageMagick/magick/version.h \
		/usr/local/include/ImageMagick/magick/mime.h \
		/usr/local/include/ImageMagick/magick/montage.h \
		/usr/local/include/ImageMagick/magick/option.h \
		/usr/local/include/ImageMagick/magick/paint.h \
		/usr/local/include/ImageMagick/magick/policy.h \
		/usr/local/include/ImageMagick/magick/prepress.h \
		/usr/local/include/ImageMagick/magick/property.h \
		/usr/local/include/ImageMagick/magick/resource_.h \
		/usr/local/include/ImageMagick/magick/segment.h \
		/usr/local/include/ImageMagick/magick/shear.h \
		/usr/local/include/ImageMagick/magick/signature.h \
		/usr/local/include/ImageMagick/magick/splay-tree.h \
		/usr/local/include/ImageMagick/magick/statistic.h \
		/usr/local/include/ImageMagick/magick/token.h \
		/usr/local/include/ImageMagick/magick/transform.h \
		/usr/local/include/ImageMagick/magick/threshold.h \
		/usr/local/include/ImageMagick/magick/utility.h \
		/usr/local/include/ImageMagick/magick/xml-tree.h \
		/usr/local/include/ImageMagick/magick/xwindow.h \
		/usr/local/include/ImageMagick/wand/MagickWand.h \
		/usr/local/include/ImageMagick/wand/method-attribute.h \
		/usr/local/include/ImageMagick/wand/animate.h \
		/usr/local/include/ImageMagick/wand/compare.h \
		/usr/local/include/ImageMagick/wand/composite.h \
		/usr/local/include/ImageMagick/wand/conjure.h \
		/usr/local/include/ImageMagick/wand/convert.h \
		/usr/local/include/ImageMagick/wand/deprecate.h \
		/usr/local/include/ImageMagick/wand/drawing-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-wand.h \
		/usr/local/include/ImageMagick/wand/magick-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-iterator.h \
		/usr/local/include/ImageMagick/wand/display.h \
		/usr/local/include/ImageMagick/wand/identify.h \
		/usr/local/include/ImageMagick/wand/import.h \
		/usr/local/include/ImageMagick/wand/magick-property.h \
		/usr/local/include/ImageMagick/wand/magick-image.h \
		/usr/local/include/ImageMagick/wand/mogrify.h \
		/usr/local/include/ImageMagick/wand/montage.h \
		/usr/local/include/ImageMagick/wand/stream.h \
		/usr/local/include/ImageMagick/wand/wand-view.h \
		/usr/local/include/ImageMagick/Magick++/Image.h \
		/usr/local/include/ImageMagick/Magick++/Blob.h \
		/usr/local/include/ImageMagick/Magick++/Color.h \
		/usr/local/include/ImageMagick/Magick++/Drawable.h \
		/usr/local/include/ImageMagick/Magick++/Geometry.h \
		/usr/local/include/ImageMagick/Magick++/Exception.h \
		/usr/local/include/ImageMagick/Magick++/TypeMetric.h \
		/usr/local/include/ImageMagick/Magick++/Pixels.h \
		/usr/local/include/ImageMagick/Magick++/STL.h \
		/usr/local/include/ImageMagick/Magick++/CoderInfo.h \
		/usr/local/include/ImageMagick/Magick++/Montage.h \
		decoder.h \
		histogramResult.h \
		encoder.h \
		numbersystemwidget.h \
		multiBase.h \
		enhancer.h \
		goldenRatioSystem.h \
		fibonacciSystem.h \
		alphaConverter.h \
		securer.h \
		chunker.h \
		compressor.h \
		analyzer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

multiBase.o: multiBase.cpp numberSystem.h \
		multiBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multiBase.o multiBase.cpp

numberSystem.o: numberSystem.cpp numberSystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numberSystem.o numberSystem.cpp

novelBarcodeDecorder.o: novelBarcodeDecorder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o novelBarcodeDecorder.o novelBarcodeDecorder.cpp

fibonacciSystem.o: fibonacciSystem.cpp numberSystem.h \
		fibonacciSystem.h \
		alphaConverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fibonacciSystem.o fibonacciSystem.cpp

decoder.o: decoder.cpp decoder.h \
		/usr/local/include/ImageMagick/Magick++.h \
		/usr/local/include/ImageMagick/Magick++/Include.h \
		/usr/local/include/ImageMagick/magick/magick-config.h \
		/usr/local/include/ImageMagick/magick/MagickCore.h \
		/usr/local/include/ImageMagick/magick/method-attribute.h \
		/usr/local/include/ImageMagick/magick/methods.h \
		/usr/local/include/ImageMagick/magick/magick-type.h \
		/usr/local/include/ImageMagick/magick/accelerate.h \
		/usr/local/include/ImageMagick/magick/morphology.h \
		/usr/local/include/ImageMagick/magick/geometry.h \
		/usr/local/include/ImageMagick/magick/animate.h \
		/usr/local/include/ImageMagick/magick/annotate.h \
		/usr/local/include/ImageMagick/magick/draw.h \
		/usr/local/include/ImageMagick/magick/image.h \
		/usr/local/include/ImageMagick/magick/color.h \
		/usr/local/include/ImageMagick/magick/pixel.h \
		/usr/local/include/ImageMagick/magick/colorspace.h \
		/usr/local/include/ImageMagick/magick/constitute.h \
		/usr/local/include/ImageMagick/magick/exception.h \
		/usr/local/include/ImageMagick/magick/semaphore.h \
		/usr/local/include/ImageMagick/magick/blob.h \
		/usr/local/include/ImageMagick/magick/stream.h \
		/usr/local/include/ImageMagick/magick/cache-view.h \
		/usr/local/include/ImageMagick/magick/composite.h \
		/usr/local/include/ImageMagick/magick/compress.h \
		/usr/local/include/ImageMagick/magick/effect.h \
		/usr/local/include/ImageMagick/magick/layer.h \
		/usr/local/include/ImageMagick/magick/locale_.h \
		/usr/local/include/ImageMagick/magick/hashmap.h \
		/usr/local/include/ImageMagick/magick/monitor.h \
		/usr/local/include/ImageMagick/magick/profile.h \
		/usr/local/include/ImageMagick/magick/string_.h \
		/usr/local/include/ImageMagick/magick/quantum.h \
		/usr/local/include/ImageMagick/magick/resample.h \
		/usr/local/include/ImageMagick/magick/resize.h \
		/usr/local/include/ImageMagick/magick/timer.h \
		/usr/local/include/ImageMagick/magick/type.h \
		/usr/local/include/ImageMagick/magick/artifact.h \
		/usr/local/include/ImageMagick/magick/attribute.h \
		/usr/local/include/ImageMagick/magick/cache.h \
		/usr/local/include/ImageMagick/magick/cipher.h \
		/usr/local/include/ImageMagick/magick/client.h \
		/usr/local/include/ImageMagick/magick/coder.h \
		/usr/local/include/ImageMagick/magick/colormap.h \
		/usr/local/include/ImageMagick/magick/compare.h \
		/usr/local/include/ImageMagick/magick/configure.h \
		/usr/local/include/ImageMagick/magick/decorate.h \
		/usr/local/include/ImageMagick/magick/delegate.h \
		/usr/local/include/ImageMagick/magick/deprecate.h \
		/usr/local/include/ImageMagick/magick/quantize.h \
		/usr/local/include/ImageMagick/magick/registry.h \
		/usr/local/include/ImageMagick/magick/display.h \
		/usr/local/include/ImageMagick/magick/distort.h \
		/usr/local/include/ImageMagick/magick/enhance.h \
		/usr/local/include/ImageMagick/magick/feature.h \
		/usr/local/include/ImageMagick/magick/fourier.h \
		/usr/local/include/ImageMagick/magick/fx.h \
		/usr/local/include/ImageMagick/magick/gem.h \
		/usr/local/include/ImageMagick/magick/random_.h \
		/usr/local/include/ImageMagick/magick/histogram.h \
		/usr/local/include/ImageMagick/magick/identify.h \
		/usr/local/include/ImageMagick/magick/image-view.h \
		/usr/local/include/ImageMagick/magick/list.h \
		/usr/local/include/ImageMagick/magick/log.h \
		/usr/local/include/ImageMagick/magick/magic.h \
		/usr/local/include/ImageMagick/magick/magick.h \
		/usr/local/include/ImageMagick/magick/matrix.h \
		/usr/local/include/ImageMagick/magick/memory_.h \
		/usr/local/include/ImageMagick/magick/module.h \
		/usr/local/include/ImageMagick/magick/version.h \
		/usr/local/include/ImageMagick/magick/mime.h \
		/usr/local/include/ImageMagick/magick/montage.h \
		/usr/local/include/ImageMagick/magick/option.h \
		/usr/local/include/ImageMagick/magick/paint.h \
		/usr/local/include/ImageMagick/magick/policy.h \
		/usr/local/include/ImageMagick/magick/prepress.h \
		/usr/local/include/ImageMagick/magick/property.h \
		/usr/local/include/ImageMagick/magick/resource_.h \
		/usr/local/include/ImageMagick/magick/segment.h \
		/usr/local/include/ImageMagick/magick/shear.h \
		/usr/local/include/ImageMagick/magick/signature.h \
		/usr/local/include/ImageMagick/magick/splay-tree.h \
		/usr/local/include/ImageMagick/magick/statistic.h \
		/usr/local/include/ImageMagick/magick/token.h \
		/usr/local/include/ImageMagick/magick/transform.h \
		/usr/local/include/ImageMagick/magick/threshold.h \
		/usr/local/include/ImageMagick/magick/utility.h \
		/usr/local/include/ImageMagick/magick/xml-tree.h \
		/usr/local/include/ImageMagick/magick/xwindow.h \
		/usr/local/include/ImageMagick/wand/MagickWand.h \
		/usr/local/include/ImageMagick/wand/method-attribute.h \
		/usr/local/include/ImageMagick/wand/animate.h \
		/usr/local/include/ImageMagick/wand/compare.h \
		/usr/local/include/ImageMagick/wand/composite.h \
		/usr/local/include/ImageMagick/wand/conjure.h \
		/usr/local/include/ImageMagick/wand/convert.h \
		/usr/local/include/ImageMagick/wand/deprecate.h \
		/usr/local/include/ImageMagick/wand/drawing-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-wand.h \
		/usr/local/include/ImageMagick/wand/magick-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-iterator.h \
		/usr/local/include/ImageMagick/wand/display.h \
		/usr/local/include/ImageMagick/wand/identify.h \
		/usr/local/include/ImageMagick/wand/import.h \
		/usr/local/include/ImageMagick/wand/magick-property.h \
		/usr/local/include/ImageMagick/wand/magick-image.h \
		/usr/local/include/ImageMagick/wand/mogrify.h \
		/usr/local/include/ImageMagick/wand/montage.h \
		/usr/local/include/ImageMagick/wand/stream.h \
		/usr/local/include/ImageMagick/wand/wand-view.h \
		/usr/local/include/ImageMagick/Magick++/Image.h \
		/usr/local/include/ImageMagick/Magick++/Blob.h \
		/usr/local/include/ImageMagick/Magick++/Color.h \
		/usr/local/include/ImageMagick/Magick++/Drawable.h \
		/usr/local/include/ImageMagick/Magick++/Geometry.h \
		/usr/local/include/ImageMagick/Magick++/Exception.h \
		/usr/local/include/ImageMagick/Magick++/TypeMetric.h \
		/usr/local/include/ImageMagick/Magick++/Pixels.h \
		/usr/local/include/ImageMagick/Magick++/STL.h \
		/usr/local/include/ImageMagick/Magick++/CoderInfo.h \
		/usr/local/include/ImageMagick/Magick++/Montage.h \
		histogramResult.h \
		numberSystem.h \
		encoder.h \
		fibonacciSystem.h \
		alphaConverter.h \
		chunker.h \
		compressor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o decoder.o decoder.cpp

numbersystemwidget.o: numbersystemwidget.cpp numbersystemwidget.h \
		numberSystem.h \
		ui_numbersystemwidget.h \
		fibonacciSystem.h \
		alphaConverter.h \
		goldenRatioSystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o numbersystemwidget.o numbersystemwidget.cpp

enhancer.o: enhancer.cpp /usr/local/include/ImageMagick/Magick++.h \
		/usr/local/include/ImageMagick/Magick++/Include.h \
		/usr/local/include/ImageMagick/magick/magick-config.h \
		/usr/local/include/ImageMagick/magick/MagickCore.h \
		/usr/local/include/ImageMagick/magick/method-attribute.h \
		/usr/local/include/ImageMagick/magick/methods.h \
		/usr/local/include/ImageMagick/magick/magick-type.h \
		/usr/local/include/ImageMagick/magick/accelerate.h \
		/usr/local/include/ImageMagick/magick/morphology.h \
		/usr/local/include/ImageMagick/magick/geometry.h \
		/usr/local/include/ImageMagick/magick/animate.h \
		/usr/local/include/ImageMagick/magick/annotate.h \
		/usr/local/include/ImageMagick/magick/draw.h \
		/usr/local/include/ImageMagick/magick/image.h \
		/usr/local/include/ImageMagick/magick/color.h \
		/usr/local/include/ImageMagick/magick/pixel.h \
		/usr/local/include/ImageMagick/magick/colorspace.h \
		/usr/local/include/ImageMagick/magick/constitute.h \
		/usr/local/include/ImageMagick/magick/exception.h \
		/usr/local/include/ImageMagick/magick/semaphore.h \
		/usr/local/include/ImageMagick/magick/blob.h \
		/usr/local/include/ImageMagick/magick/stream.h \
		/usr/local/include/ImageMagick/magick/cache-view.h \
		/usr/local/include/ImageMagick/magick/composite.h \
		/usr/local/include/ImageMagick/magick/compress.h \
		/usr/local/include/ImageMagick/magick/effect.h \
		/usr/local/include/ImageMagick/magick/layer.h \
		/usr/local/include/ImageMagick/magick/locale_.h \
		/usr/local/include/ImageMagick/magick/hashmap.h \
		/usr/local/include/ImageMagick/magick/monitor.h \
		/usr/local/include/ImageMagick/magick/profile.h \
		/usr/local/include/ImageMagick/magick/string_.h \
		/usr/local/include/ImageMagick/magick/quantum.h \
		/usr/local/include/ImageMagick/magick/resample.h \
		/usr/local/include/ImageMagick/magick/resize.h \
		/usr/local/include/ImageMagick/magick/timer.h \
		/usr/local/include/ImageMagick/magick/type.h \
		/usr/local/include/ImageMagick/magick/artifact.h \
		/usr/local/include/ImageMagick/magick/attribute.h \
		/usr/local/include/ImageMagick/magick/cache.h \
		/usr/local/include/ImageMagick/magick/cipher.h \
		/usr/local/include/ImageMagick/magick/client.h \
		/usr/local/include/ImageMagick/magick/coder.h \
		/usr/local/include/ImageMagick/magick/colormap.h \
		/usr/local/include/ImageMagick/magick/compare.h \
		/usr/local/include/ImageMagick/magick/configure.h \
		/usr/local/include/ImageMagick/magick/decorate.h \
		/usr/local/include/ImageMagick/magick/delegate.h \
		/usr/local/include/ImageMagick/magick/deprecate.h \
		/usr/local/include/ImageMagick/magick/quantize.h \
		/usr/local/include/ImageMagick/magick/registry.h \
		/usr/local/include/ImageMagick/magick/display.h \
		/usr/local/include/ImageMagick/magick/distort.h \
		/usr/local/include/ImageMagick/magick/enhance.h \
		/usr/local/include/ImageMagick/magick/feature.h \
		/usr/local/include/ImageMagick/magick/fourier.h \
		/usr/local/include/ImageMagick/magick/fx.h \
		/usr/local/include/ImageMagick/magick/gem.h \
		/usr/local/include/ImageMagick/magick/random_.h \
		/usr/local/include/ImageMagick/magick/histogram.h \
		/usr/local/include/ImageMagick/magick/identify.h \
		/usr/local/include/ImageMagick/magick/image-view.h \
		/usr/local/include/ImageMagick/magick/list.h \
		/usr/local/include/ImageMagick/magick/log.h \
		/usr/local/include/ImageMagick/magick/magic.h \
		/usr/local/include/ImageMagick/magick/magick.h \
		/usr/local/include/ImageMagick/magick/matrix.h \
		/usr/local/include/ImageMagick/magick/memory_.h \
		/usr/local/include/ImageMagick/magick/module.h \
		/usr/local/include/ImageMagick/magick/version.h \
		/usr/local/include/ImageMagick/magick/mime.h \
		/usr/local/include/ImageMagick/magick/montage.h \
		/usr/local/include/ImageMagick/magick/option.h \
		/usr/local/include/ImageMagick/magick/paint.h \
		/usr/local/include/ImageMagick/magick/policy.h \
		/usr/local/include/ImageMagick/magick/prepress.h \
		/usr/local/include/ImageMagick/magick/property.h \
		/usr/local/include/ImageMagick/magick/resource_.h \
		/usr/local/include/ImageMagick/magick/segment.h \
		/usr/local/include/ImageMagick/magick/shear.h \
		/usr/local/include/ImageMagick/magick/signature.h \
		/usr/local/include/ImageMagick/magick/splay-tree.h \
		/usr/local/include/ImageMagick/magick/statistic.h \
		/usr/local/include/ImageMagick/magick/token.h \
		/usr/local/include/ImageMagick/magick/transform.h \
		/usr/local/include/ImageMagick/magick/threshold.h \
		/usr/local/include/ImageMagick/magick/utility.h \
		/usr/local/include/ImageMagick/magick/xml-tree.h \
		/usr/local/include/ImageMagick/magick/xwindow.h \
		/usr/local/include/ImageMagick/wand/MagickWand.h \
		/usr/local/include/ImageMagick/wand/method-attribute.h \
		/usr/local/include/ImageMagick/wand/animate.h \
		/usr/local/include/ImageMagick/wand/compare.h \
		/usr/local/include/ImageMagick/wand/composite.h \
		/usr/local/include/ImageMagick/wand/conjure.h \
		/usr/local/include/ImageMagick/wand/convert.h \
		/usr/local/include/ImageMagick/wand/deprecate.h \
		/usr/local/include/ImageMagick/wand/drawing-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-wand.h \
		/usr/local/include/ImageMagick/wand/magick-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-iterator.h \
		/usr/local/include/ImageMagick/wand/display.h \
		/usr/local/include/ImageMagick/wand/identify.h \
		/usr/local/include/ImageMagick/wand/import.h \
		/usr/local/include/ImageMagick/wand/magick-property.h \
		/usr/local/include/ImageMagick/wand/magick-image.h \
		/usr/local/include/ImageMagick/wand/mogrify.h \
		/usr/local/include/ImageMagick/wand/montage.h \
		/usr/local/include/ImageMagick/wand/stream.h \
		/usr/local/include/ImageMagick/wand/wand-view.h \
		/usr/local/include/ImageMagick/Magick++/Image.h \
		/usr/local/include/ImageMagick/Magick++/Blob.h \
		/usr/local/include/ImageMagick/Magick++/Color.h \
		/usr/local/include/ImageMagick/Magick++/Drawable.h \
		/usr/local/include/ImageMagick/Magick++/Geometry.h \
		/usr/local/include/ImageMagick/Magick++/Exception.h \
		/usr/local/include/ImageMagick/Magick++/TypeMetric.h \
		/usr/local/include/ImageMagick/Magick++/Pixels.h \
		/usr/local/include/ImageMagick/Magick++/STL.h \
		/usr/local/include/ImageMagick/Magick++/CoderInfo.h \
		/usr/local/include/ImageMagick/Magick++/Montage.h \
		enhancer.h \
		numberSystem.h \
		goldenRatioSystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enhancer.o enhancer.cpp

goldenRatioSystem.o: goldenRatioSystem.cpp numberSystem.h \
		goldenRatioSystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goldenRatioSystem.o goldenRatioSystem.cpp

chunker.o: chunker.cpp numberSystem.h \
		chunker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chunker.o chunker.cpp

encoder.o: encoder.cpp encoder.h \
		/usr/local/include/ImageMagick/Magick++.h \
		/usr/local/include/ImageMagick/Magick++/Include.h \
		/usr/local/include/ImageMagick/magick/magick-config.h \
		/usr/local/include/ImageMagick/magick/MagickCore.h \
		/usr/local/include/ImageMagick/magick/method-attribute.h \
		/usr/local/include/ImageMagick/magick/methods.h \
		/usr/local/include/ImageMagick/magick/magick-type.h \
		/usr/local/include/ImageMagick/magick/accelerate.h \
		/usr/local/include/ImageMagick/magick/morphology.h \
		/usr/local/include/ImageMagick/magick/geometry.h \
		/usr/local/include/ImageMagick/magick/animate.h \
		/usr/local/include/ImageMagick/magick/annotate.h \
		/usr/local/include/ImageMagick/magick/draw.h \
		/usr/local/include/ImageMagick/magick/image.h \
		/usr/local/include/ImageMagick/magick/color.h \
		/usr/local/include/ImageMagick/magick/pixel.h \
		/usr/local/include/ImageMagick/magick/colorspace.h \
		/usr/local/include/ImageMagick/magick/constitute.h \
		/usr/local/include/ImageMagick/magick/exception.h \
		/usr/local/include/ImageMagick/magick/semaphore.h \
		/usr/local/include/ImageMagick/magick/blob.h \
		/usr/local/include/ImageMagick/magick/stream.h \
		/usr/local/include/ImageMagick/magick/cache-view.h \
		/usr/local/include/ImageMagick/magick/composite.h \
		/usr/local/include/ImageMagick/magick/compress.h \
		/usr/local/include/ImageMagick/magick/effect.h \
		/usr/local/include/ImageMagick/magick/layer.h \
		/usr/local/include/ImageMagick/magick/locale_.h \
		/usr/local/include/ImageMagick/magick/hashmap.h \
		/usr/local/include/ImageMagick/magick/monitor.h \
		/usr/local/include/ImageMagick/magick/profile.h \
		/usr/local/include/ImageMagick/magick/string_.h \
		/usr/local/include/ImageMagick/magick/quantum.h \
		/usr/local/include/ImageMagick/magick/resample.h \
		/usr/local/include/ImageMagick/magick/resize.h \
		/usr/local/include/ImageMagick/magick/timer.h \
		/usr/local/include/ImageMagick/magick/type.h \
		/usr/local/include/ImageMagick/magick/artifact.h \
		/usr/local/include/ImageMagick/magick/attribute.h \
		/usr/local/include/ImageMagick/magick/cache.h \
		/usr/local/include/ImageMagick/magick/cipher.h \
		/usr/local/include/ImageMagick/magick/client.h \
		/usr/local/include/ImageMagick/magick/coder.h \
		/usr/local/include/ImageMagick/magick/colormap.h \
		/usr/local/include/ImageMagick/magick/compare.h \
		/usr/local/include/ImageMagick/magick/configure.h \
		/usr/local/include/ImageMagick/magick/decorate.h \
		/usr/local/include/ImageMagick/magick/delegate.h \
		/usr/local/include/ImageMagick/magick/deprecate.h \
		/usr/local/include/ImageMagick/magick/quantize.h \
		/usr/local/include/ImageMagick/magick/registry.h \
		/usr/local/include/ImageMagick/magick/display.h \
		/usr/local/include/ImageMagick/magick/distort.h \
		/usr/local/include/ImageMagick/magick/enhance.h \
		/usr/local/include/ImageMagick/magick/feature.h \
		/usr/local/include/ImageMagick/magick/fourier.h \
		/usr/local/include/ImageMagick/magick/fx.h \
		/usr/local/include/ImageMagick/magick/gem.h \
		/usr/local/include/ImageMagick/magick/random_.h \
		/usr/local/include/ImageMagick/magick/histogram.h \
		/usr/local/include/ImageMagick/magick/identify.h \
		/usr/local/include/ImageMagick/magick/image-view.h \
		/usr/local/include/ImageMagick/magick/list.h \
		/usr/local/include/ImageMagick/magick/log.h \
		/usr/local/include/ImageMagick/magick/magic.h \
		/usr/local/include/ImageMagick/magick/magick.h \
		/usr/local/include/ImageMagick/magick/matrix.h \
		/usr/local/include/ImageMagick/magick/memory_.h \
		/usr/local/include/ImageMagick/magick/module.h \
		/usr/local/include/ImageMagick/magick/version.h \
		/usr/local/include/ImageMagick/magick/mime.h \
		/usr/local/include/ImageMagick/magick/montage.h \
		/usr/local/include/ImageMagick/magick/option.h \
		/usr/local/include/ImageMagick/magick/paint.h \
		/usr/local/include/ImageMagick/magick/policy.h \
		/usr/local/include/ImageMagick/magick/prepress.h \
		/usr/local/include/ImageMagick/magick/property.h \
		/usr/local/include/ImageMagick/magick/resource_.h \
		/usr/local/include/ImageMagick/magick/segment.h \
		/usr/local/include/ImageMagick/magick/shear.h \
		/usr/local/include/ImageMagick/magick/signature.h \
		/usr/local/include/ImageMagick/magick/splay-tree.h \
		/usr/local/include/ImageMagick/magick/statistic.h \
		/usr/local/include/ImageMagick/magick/token.h \
		/usr/local/include/ImageMagick/magick/transform.h \
		/usr/local/include/ImageMagick/magick/threshold.h \
		/usr/local/include/ImageMagick/magick/utility.h \
		/usr/local/include/ImageMagick/magick/xml-tree.h \
		/usr/local/include/ImageMagick/magick/xwindow.h \
		/usr/local/include/ImageMagick/wand/MagickWand.h \
		/usr/local/include/ImageMagick/wand/method-attribute.h \
		/usr/local/include/ImageMagick/wand/animate.h \
		/usr/local/include/ImageMagick/wand/compare.h \
		/usr/local/include/ImageMagick/wand/composite.h \
		/usr/local/include/ImageMagick/wand/conjure.h \
		/usr/local/include/ImageMagick/wand/convert.h \
		/usr/local/include/ImageMagick/wand/deprecate.h \
		/usr/local/include/ImageMagick/wand/drawing-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-wand.h \
		/usr/local/include/ImageMagick/wand/magick-wand.h \
		/usr/local/include/ImageMagick/wand/pixel-iterator.h \
		/usr/local/include/ImageMagick/wand/display.h \
		/usr/local/include/ImageMagick/wand/identify.h \
		/usr/local/include/ImageMagick/wand/import.h \
		/usr/local/include/ImageMagick/wand/magick-property.h \
		/usr/local/include/ImageMagick/wand/magick-image.h \
		/usr/local/include/ImageMagick/wand/mogrify.h \
		/usr/local/include/ImageMagick/wand/montage.h \
		/usr/local/include/ImageMagick/wand/stream.h \
		/usr/local/include/ImageMagick/wand/wand-view.h \
		/usr/local/include/ImageMagick/Magick++/Image.h \
		/usr/local/include/ImageMagick/Magick++/Blob.h \
		/usr/local/include/ImageMagick/Magick++/Color.h \
		/usr/local/include/ImageMagick/Magick++/Drawable.h \
		/usr/local/include/ImageMagick/Magick++/Geometry.h \
		/usr/local/include/ImageMagick/Magick++/Exception.h \
		/usr/local/include/ImageMagick/Magick++/TypeMetric.h \
		/usr/local/include/ImageMagick/Magick++/Pixels.h \
		/usr/local/include/ImageMagick/Magick++/STL.h \
		/usr/local/include/ImageMagick/Magick++/CoderInfo.h \
		/usr/local/include/ImageMagick/Magick++/Montage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encoder.o encoder.cpp

securer.o: securer.cpp securer.h \
		numberSystem.h \
		fibonacciSystem.h \
		alphaConverter.h \
		goldenRatioSystem.h \
		multiBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o securer.o securer.cpp

compressor.o: compressor.cpp chunker.h \
		numberSystem.h \
		compressor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compressor.o compressor.cpp

alphaConverter.o: alphaConverter.cpp alphaConverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alphaConverter.o alphaConverter.cpp

analyzer.o: analyzer.cpp analyzer.h \
		numberSystem.h \
		chunker.h \
		alphaConverter.h \
		compressor.h \
		multiBase.h \
		fibonacciSystem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analyzer.o analyzer.cpp

code39_Encoder.o: code39_Encoder.cpp code39_Encoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o code39_Encoder.o code39_Encoder.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_numbersystemwidget.o: moc_numbersystemwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_numbersystemwidget.o moc_numbersystemwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

